import { buildReveal } from './grid.js';
import { save } from './state.js';
import { stopTimer } from './timer/timer.js';
import { checkWorldCompleteAch, onLevelCompleteAch } from './achievements/achievements.js';
import { Audio_Manager } from './audio/audio.js';
import { t } from './translation/translations.js';
import { _incDirect, questStat_luckyDropClaimed, updateQuestStats } from './inference/inference-stats.js';
import { ptHasSkill } from './passive-tree/passive-tree-state-points.js';
import { goToLevelSelect, hideResultOverlays } from './screens/screens.js';
import { _wdSyncSpriteToLevel } from './screens/screens-world-levels.js';
import { _ptApplyLevelCompleteRewards } from './passive-tree/passive-tree.js';
import { STATE } from './state.js';
import { cur } from './state.js';


//------------------------------------------------------------------------
// Phase 3 step 3: live globalThis accessors for externally-mutated state.
// (auto-generated by dev/scratch/convert-step3.mjs - do not edit by hand)
//------------------------------------------------------------------------
try { Object.defineProperty(globalThis, 'checkWin', { get() { return checkWin; }, set(v) { checkWin = v; }, configurable: true }); } catch (e) {}
// =============================================================================
// scoring.js
// Handles all end-of-level scoring logic: puzzle validation, score calculation,
// bonus evaluation, lucky drops, achievement hooks, special rewards, win overlay
// rendering, and the main checkWin() entry point.
// =============================================================================


//------------------------------------------------------------------------
//-------------------MODULE-LEVEL STATE-----------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Tracks points earned during the current active run.
// Set inside calculateScore() when a level is completed and referenced by
// the win overlay to show how many points were awarded vs. the previous best.
export let currentRunScore = 0;


//------------------------------------------------------------------------
//-------------------PUZZLE VALIDATION------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Returns true if every cell in the player's grid matches the solution.
// A cell counts as "filled" if the player marked it (userGrid === 1)
// or if it was revealed by a helper item (revealedGrid === true).
export function isPuzzleSolved() {
    const sol = cur.grid;
    const rows = sol.length;
    const cols = sol[0].length;

    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
            const playerFilled = globalThis.userGrid[r][c] === 1 || globalThis.revealedGrid[r][c];
            const solutionFilled = sol[r][c] === 1;
            if (playerFilled !== solutionFilled) return false;
        }
    }
    return true;
}


//------------------------------------------------------------------------
//-------------------SCORE CALCULATION------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Returns the raw score before the multiplier is applied.
// Base score grows with grid size; remaining time adds a bonus;
// each mistake deducts points. Score is floored at 10.
export function computeRawScore(rows, cols) {
    const safeRows = Number.isFinite(Number(rows)) ? Number(rows) : 0;
    const safeCols = Number.isFinite(Number(cols)) ? Number(cols) : 0;
    const baseScore = 100 + (safeRows + safeCols) * 2;

    // Time Trial halves the starting clock, which would otherwise also halve
    // the time bonus. Add back exactly what was cut so the bonus reflects
    // the same effective time budget as normal mode.
    const normalizedSecs = globalThis.timerSecs + (globalThis.curMods.timetrial ? (window._timetrialTimeCut || 0) : 0);

    const safeTimerSecs = Number.isFinite(Number(globalThis.timerSecs)) ? Number(globalThis.timerSecs) : 0;
    const safeNormalizedSecs = Number.isFinite(Number(normalizedSecs)) ? Number(normalizedSecs) : safeTimerSecs;
    const cappedTime = Math.min(Math.max(0, safeNormalizedSecs), 3600);   // cap at 1 hour to prevent abuse
    const timeBonus = Math.floor(cappedTime / 10);
    const safeMistakes = Number.isFinite(Number(globalThis.mistakeCount)) ? Number(globalThis.mistakeCount) : 0;
    const mistakePenalty = safeMistakes * 20;
    return Math.max(10, baseScore + timeBonus - mistakePenalty);
}

// Determines how many net-new points are awarded to the player.
// If the current run score beats the level high score, the difference is awarded.
// Otherwise nothing is awarded (the player already has a better record).
export function computePointsAwarded(pts, gi) {
    const hs = STATE.levelHS[gi];
    const prevBest = hs ? hs.score : 0;
    return { ptsAwarded: Math.max(0, pts - prevBest), prevBest };
}

// Saves a new high-score entry for this level if the current run beats the record.
export function maybeUpdateHighScore(gi, pts) {
    const hs = STATE.levelHS[gi];
    if (!hs || pts > hs.score) {
        STATE.levelHS[gi] = {
            score: pts,
            diff: globalThis.curDiff,
            time: globalThis.timerSecs,
            mods: { ...globalThis.curMods },
        };
    }
}

// Master score calculation function.
// Computes the final score, awards net-new points to the player's total,
// updates the level high score if beaten, and returns all relevant values
// for display and quest-stat tracking.
export function calculateScore(rows, cols) {
    const gi = cur.gIdx;
    const rawScore = computeRawScore(rows, cols);
    const calculatedMult = globalThis.scoreMultiplier();
    const mult = Number.isFinite(Number(calculatedMult)) ? Number(calculatedMult) : 1;
    const calculatedPts = Math.round(rawScore * mult);
    const pts = Number.isFinite(calculatedPts) ? Math.max(0, calculatedPts) : 0;

    const { ptsAwarded, prevBest } = computePointsAwarded(pts, gi);

    const currentTotal = Number.isFinite(Number(STATE.totalScore)) ? Number(STATE.totalScore) : 0;
    STATE.totalScore = currentTotal + ptsAwarded;
    maybeUpdateHighScore(gi, pts);

    return { pts, ptsAwarded, prevBest, mult };
}


//------------------------------------------------------------------------
//-------------------BONUS OBJECTIVE EVALUATION---------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Returns true if the current level's bonus condition has been satisfied.
// Each bonusType has its own pass/fail rule; unknown types default to false.
export function evaluateBonusObjective(elapsed) {
    const bt = cur.bonusType || 'nomiss';
    const bp = cur.bonusParam !== undefined ? cur.bonusParam : 0;

    switch (bt) {
        case 'fast': return elapsed <= bp;
        case 'nomiss': return globalThis.mistakeCount === 0;
        case 'lowmiss': return globalThis.mistakeCount <= bp;
        case 'noitem': return globalThis.itemsUsedThisLevel === 0;
        case 'quiz': return true;   // quiz bonus is evaluated separately via showQuiz()
        case 'combo': return elapsed <= bp && globalThis.mistakeCount === 0;
        case 'noitem_nomiss': return globalThis.itemsUsedThisLevel === 0 && globalThis.mistakeCount === 0;
        case 'noitem_fast': return globalThis.itemsUsedThisLevel === 0 && elapsed <= bp;
        default: return false;
    }
}


//------------------------------------------------------------------------
//-------------------ACHIEVEMENT HOOKS------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Counts how many solution cells are filled (value === 1) in the grid.
export function countFilledCells(sol, rows, cols) {
    let count = 0;
    for (let r = 0; r < rows; r++)
        for (let c = 0; c < cols; c++)
            if (sol[r][c] === 1) count++;
    return count;
}

// Counts how many cells the player has cross-marked (userGrid value === 2).
export function countMarkedCells(rows, cols) {
    if (!globalThis.userGrid) return 0;
    let count = 0;
    for (let r = 0; r < rows; r++)
        for (let c = 0; c < cols; c++)
            if (globalThis.userGrid[r][c] === 2) count++;
    return count;
}

// Fires the achievement system's level-complete hook with all relevant stats,
// then clears the per-run window flags used by penalty-clutch and bounceback logic.
export function fireAchievements({ gi, rows, cols, elapsed, pts, ptsAwarded, prevBest, mult, isFirstClear }) {
    const sol = cur.grid;
    const totalCells = rows * cols;
    const cellsFilled = countFilledCells(sol, rows, cols);
    const tilesMarked = countMarkedCells(rows, cols);

    onLevelCompleteAch({
        mistakes: globalThis.mistakeCount,
        itemsUsed: globalThis.itemsUsedThisLevel,
        diff: globalThis.curDiff,
        mods: globalThis.curMods,
        playerClass: STATE.playerClass || null,
        playerAscendency: STATE.playerAscendency || null,
        absorbedMistakes: globalThis.absorbedMistakes,
        absorbedThisLevel: globalThis.absorbedMistakes,
        cellsFilled,
        tilesMarked,
        totalCells,
        rows,
        cols,
        scoreEarned: pts,
        world: cur.world,
        gi,
        elapsed,
        timerSecs: globalThis.timerSecs,
        pts,
        prevBest,
        mult,
        isFirstClear,
        hadPenaltyClutch: !!window._hadPenaltyClutch,
        isBouncebackWin: window._lastFailedGi === gi,
    });

    // Reset transient run flags consumed by the achievement system
    window._hadPenaltyClutch = false;
    window._lastFailedGi = null;

    checkWorldCompleteAch();
}


//------------------------------------------------------------------------
//-------------------ITEM REWARD HELPERS-----------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Wraps reward content in the standard item-reward card markup shared by
// bonus rewards, lucky drops, and the ascension codex reward.
export function _buildItemRewardCard(defId, def, labelHtml) {
    const rc = globalThis.rarityColors(def.rarity);
    return `
        <div class="item-reward" data-reward-defid="${defId}"
             style="border-color:${rc.border};color:${rc.color};cursor:default;">
            ${labelHtml}
        </div>`;
}


//------------------------------------------------------------------------
//-------------------CONVERGENCE REWARD-----------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Convergence milestones no longer live on campaign puzzle levels (Leveling
// Rework): every former convergence level is a REGULAR puzzle level now.
// Passive points for milestones come from Convergence Trials instead (see
// js/campaign-trials.js). Kept as a function because quest stats, the world
// screens and old saves still call it; it always reports "not convergence".
export function isConvergenceLevel(worldData, isAscensionLevel) {
    return false;
}

// Grants one passive tree point on the first clear of a convergence level
// and queues the convergence modal for display after the win overlay closes.

export function applyConvergenceReward(gi) {
    if (!STATE.convergenceDone) STATE.convergenceDone = [];
    const isFirstEver = STATE.convergenceDone.length === 0;
    STATE.convergenceDone.push(gi);
    STATE.passiveTreePoints = (STATE.passiveTreePoints || 0) + 1;
    _incDirect('lifetimePassivePointsObtained', 1);
    save();
    window._pendingConvergenceModal = true;

    if (isFirstEver) {
        //showBeat('first_convergence');
    }
}


//------------------------------------------------------------------------
//-------------------ASCENSION REWARD-------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Grants the Codex of Completion artifact on the first clear of the final
// level in a world (the ascension level), and writes its reward HTML into irz.
// Does nothing in ironman mode - that mode disables item rewards.
export function applyAscensionReward(irz) {
    const defId = 'artifactComplete';
    const codexDef = globalThis.ITEM_DEFS[defId];

    STATE.inventory.push({
        defId,
        uid: `item_${Date.now()}_${Math.random().toString(36).slice(2)}`,
    });
    save();

    globalThis.buildInventoryPanel();
    globalThis.showItemGainPopup(defId);

    const label = `🌟 ${t('cg_ascension_reward')}:
            ${codexDef.icon} <strong>${globalThis.itemName(codexDef)}</strong>`;
    irz.innerHTML = _buildItemRewardCard(defId, codexDef, label);
}

// Builds the Nexus Point unlock card shown in the win overlay's reward zone.
export function applyNexusPointReward(irz) {
    if (typeof globalThis.setNexusUnlocked === 'function') globalThis.setNexusUnlocked();
    else if (typeof STATE !== 'undefined' && STATE) {
        STATE.nexusUnlocked = true;
        if (typeof save === 'function') save();
    }
    if (!irz) return;
    const label = `🌌 ${t('scr_nexus_unlocked_title')}: ${t('scr_enter_nexus_short')}`;
    irz.innerHTML += `<div class="item-reward" style="border-color:#7fd4ff;color:#bfe9ff;cursor:default;">${label}<br><span style="opacity:0.8;font-size:0.9em">${t('scr_nexus_unlocked_desc')}</span></div>`;
    if (typeof globalThis.showToast === 'function') globalThis.showToast(`🌌 ${t('scr_nexus_unlocked_title')}`);
}

// Dispatcher for convergence, ascension and Nexus Point one-time rewards.
// Called during win-overlay rendering; writes into the item-reward zone (irz)
// when a special reward applies. The Nexus Point never grants the ascension
// codex - it unlocks the Nexus instead.
export function handleSpecialRewards({ gi, isFirstClear, isAscensionLevel, irz, isNexusPoint }) {
    const worldData = globalThis.WORLDS[cur.world - 1];

    if (isConvergenceLevel(worldData, isAscensionLevel) && isFirstClear) {
        applyConvergenceReward(gi);
    }

    if (isNexusPoint) {
        if (isFirstClear) applyNexusPointReward(irz);
        return;
    }

    if (isAscensionLevel && isFirstClear && !globalThis.curMods.ironman) {
        applyAscensionReward(irz);
    }
}


//------------------------------------------------------------------------
//-------------------LUCKY DROPS------------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Returns the total drop chance for lucky drops based on allocated passive nodes.
// Base chance is 25%; each bonus_replay node adds an additional percentage.
export function getLuckyDropChance() {
    let chance = 0.25;
    if (ptHasSkill('bonus_replay_1')) chance += 0.10;
    if (ptHasSkill('bonus_replay_2')) chance += 0.15;
    if (ptHasSkill('bonus_replay_3')) chance += 0.20;
    if (globalThis._charIs('trix')) chance += 0.15;
    return chance;
}

// Returns the chance of receiving a second lucky drop item.
// Each lucky_replay node contributes an additive percentage.
export function getExtraItemChance() {
    return (ptHasSkill('lucky_replay_1') ? 0.10 : 0)
        + (ptHasSkill('lucky_replay_2') ? 0.15 : 0)
        + (ptHasSkill('lucky_replay_3') ? 0.20 : 0);
}

// Decides how many lucky drop items to grant this trigger (1 or 2).
export function rollLuckyDropCount() {
    return Math.random() < getExtraItemChance() ? 2 : 1;
}

// Builds the HTML for a single lucky-drop item reward and adds it to the inventory.
export function grantLuckyDropItem() {
    const defId = globalThis.pickRandomItem();
    if (!defId) return '';

    const def = globalThis.ITEM_DEFS[defId];
    if (!def) return '';

    STATE.inventory.push({ defId, uid: Date.now() + Math.random().toString(36).slice(2) });

    globalThis.buildInventoryPanel();
    globalThis.showItemGainPopup(defId);

    const label = `${t('ov_lucky_drop')} ${def.icon} <strong>${globalThis.itemName(def)}</strong>`;
    return _buildItemRewardCard(defId, def, label);
}

// Attempts to trigger lucky drops for this level completion.
// Requires the lucky_drops passive node to be allocated.
// Returns an HTML string of all item-reward divs granted, or '' if none triggered.
export function rollLuckyDrops() {
    if (!ptHasSkill('lucky_drops') && !globalThis._charIs('trix')) return '';
    if (Math.random() >= getLuckyDropChance()) return '';

    questStat_luckyDropClaimed();

    const count = rollLuckyDropCount();
    let html = '';
    for (let i = 0; i < count; i++) {
        html += grantLuckyDropItem();
    }

    if (html) save();
    return html;
}


//------------------------------------------------------------------------
//-------------------WIN OVERLAY HELPERS----------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Formats a time in seconds as "M:SS".
export function formatTime(totalSeconds) {
    const mins = Math.floor(totalSeconds / 60);
    const secs = totalSeconds % 60;
    return `${mins}:${String(secs).padStart(2, '0')}`;
}

// Builds the gain-note string shown next to the score.
// If a new record was set, shows the net-new points and the previous best.
// Otherwise shows just the total points awarded.
export function buildGainNote(pts, ptsAwarded, prevBest) {
    if (ptsAwarded < pts) {
        return ` (+${ptsAwarded} ${t('ov_win_new')} - ${t('ov_win_best_was')} ${prevBest})`;
    }
    return ` (+${ptsAwarded})`;
}

// Returns the appropriate HTML line for the mistake count.
// Handles the three distinct display states: no mistakes, all absorbed, partial absorbed.
export function buildMistakeLine() {
    const totalWrongClicks = globalThis.mistakeCount + globalThis.absorbedMistakes;

    if (totalWrongClicks === 0) {
        return `<div class="ov-sub-line ov-sub-miss-ok">✗ 0 ${t('ov_win_mistakes')}</div>`;
    }

    const absorbedNote = `<span style="opacity:0.55;font-size:0.85em">(${globalThis.absorbedMistakes} ${t('ov_win_absorbed')})</span>`;

    if (globalThis.absorbedMistakes > 0 && globalThis.mistakeCount === 0) {
        // All wrong clicks were absorbed - still shows as a clean run
        return `<div class="ov-sub-line ov-sub-miss-ok">✗ 0 ${t('ov_win_mistakes')} ${absorbedNote}</div>`;
    }

    const mistakeWord = globalThis.mistakeCount !== 1 ? t('ov_win_mistakes') : t('ov_win_mistake');
    const cssClass = globalThis.mistakeCount === 0 ? 'ov-sub-miss-ok' : 'ov-sub-miss';

    if (globalThis.absorbedMistakes > 0) {
        return `<div class="ov-sub-line ${cssClass}">✗ ${globalThis.mistakeCount} ${mistakeWord} ${absorbedNote}</div>`;
    }

    return `<div class="ov-sub-line ${cssClass}">✗ ${globalThis.mistakeCount} ${mistakeWord}</div>`;
}

export function buildScoreColumn(pts, ptsAwarded, prevBest, mult) {
    const safeMult = Number.isFinite(Number(mult)) ? Number(mult) : 1;
    const gainNote = buildGainNote(pts, ptsAwarded, prevBest);
    document.getElementById('ov-col-score').innerHTML = `
        <div class="ov-sub-line ov-sub-pts">${pts} ${t('ov_win_pts')}</div>
        <div class="ov-sub-line ov-sub-pts">${t('ov_win_multiplier')} ×${safeMult.toFixed(2)}</div>
        <div class="ov-sub-line ov-sub-pts">${gainNote}</div>`;
}

export function buildTimeColumn(elapsed) {
    document.getElementById('ov-col-time').innerHTML = `
        <div class="ov-sub-line ov-sub-time">
            ⏱ ${formatTime(globalThis.timerSecs)} ${t('ov_win_left')} · ${t('ov_win_solved_in')} ${formatTime(elapsed)}
        </div>
        ${buildMistakeLine()}`;
}

// Writes the bonus badge into #bonus-list.
// Shows a success badge if the bonus was met, or the bonus hint if it was missed.
export function renderBonusBadge(bonusMet) {
    document.getElementById('bonus-list').innerHTML = `
        <span class="bonus-badge ${bonusMet ? 'earned' : 'missed'}">
            ${bonusMet ? t('ov_bonus_met') : '🎯 ' + globalThis.lvText(cur, 'bonusHint')}
        </span>`;
}

// Builds the HTML for a guaranteed first-time bonus item reward,
// adds it to the inventory, and saves.
export function grantBonusItem() {
    const defId = globalThis.pickRandomItem();
    if (!defId) return '';

    const def = globalThis.ITEM_DEFS[defId];
    if (!def) return '';

    STATE.inventory.push({ defId, uid: Date.now() + Math.random().toString(36).slice(2) });
    save();

    globalThis.buildInventoryPanel();
    globalThis.showItemGainPopup(defId);

    const label = `${t('ov_item_earned')}: ${def.icon} <strong>${globalThis.itemName(def)}</strong>`;
    return _buildItemRewardCard(defId, def, label);
}

// Returns the HTML for the "bonus already claimed" notice shown on repeat clears.
export function buildBonusClaimedNote() {
    return `<div class="item-reward" style="border-color:var(--border2);color:#666;">
        ${t('ov_bonus_claimed_note')}
    </div>`;
}

// Writes item rewards into the item-reward zone (irz) based on bonus state.
// Priority order:
//   1. First-time bonus clear → guaranteed item
//   2. Repeat bonus clear     → "already claimed" note + lucky drop chance
//   3. Bonus missed           → lucky drop chance only
// Ironman mode and quiz bonuses suppress all item rewards.
export function renderItemRewardZone(gi, bonusMet, isFirstClear, isAscensionLevel, isNexusPoint) {
    const irz = document.getElementById('item-reward-zone');
    irz.innerHTML = '';
    const bonusAlreadyDone = STATE.bonusDone.includes(gi);
    const isQuizBonus = cur.bonusType === 'quiz';

    // Special one-time rewards (convergence points, ascension codex, Nexus unlock) go first
    handleSpecialRewards({ gi, isFirstClear, isAscensionLevel, irz, isNexusPoint });

    // Mark the bonus as done on first clear (before item logic so save() is called once)
    if (bonusMet && !bonusAlreadyDone && !isQuizBonus) {
        STATE.bonusDone.push(gi);
        save();
        // Re-check world aggregates - claiming this bonus may have completed
        // the "all bonuses in a world" achievement set.
        if (typeof checkWorldCompleteAch === 'function') checkWorldCompleteAch();
    }

    // Item drops are suppressed in ironman mode and for quiz bonus levels
    if (globalThis.curMods.ironman || isQuizBonus) return;

    if (bonusMet && !bonusAlreadyDone) {
        irz.innerHTML += grantBonusItem();
    } else if (bonusMet && bonusAlreadyDone) {
        irz.innerHTML += buildBonusClaimedNote();
        irz.innerHTML += rollLuckyDrops();
    } else {
        irz.innerHTML += rollLuckyDrops();
    }

    // Attach hover tooltips to every item-reward card
    setTimeout(() => {
        irz.querySelectorAll('[data-reward-defid]').forEach(el => {
            globalThis.attachItemTooltip(el, el.dataset.rewardDefid);
        });
    }, 0);
}

// Orchestrates the full win overlay render: stats, bonus badge, and item rewards.
export function renderWinOverlay({ gi, pts, ptsAwarded, prevBest, mult, elapsed, bonusMet, isAscensionLevel, isFirstClear, isNexusPoint }) {
    document.getElementById('ov-reveal-quote').innerHTML = `"${globalThis.lvText(cur, 'reveal')}"`;
    buildScoreColumn(pts, ptsAwarded, prevBest, mult);
    buildTimeColumn(elapsed);
    renderBonusBadge(bonusMet);
    renderItemRewardZone(gi, bonusMet, isFirstClear, isAscensionLevel, isNexusPoint);

    // Ascension levels always route back to the overworld: hide Next/Retry
    // and promote the Levels button to the primary action.
    // The Nexus Point behaves the same, but gains a dedicated gateway
    // button into the Nexus screen (separate element, so the static
    // Next/Levels handlers wired in title-bindings.js keep working untouched).
    const nextBtn = document.getElementById('btn-next-lvl');
    const retryBtn = document.getElementById('btn-win-retry');
    const levelsBtn = document.getElementById('btn-win-levels');
    const endOfLine = isAscensionLevel || isNexusPoint;
    if (nextBtn) nextBtn.style.display = endOfLine ? 'none' : '';
    if (retryBtn) retryBtn.style.display = endOfLine ? 'none' : '';
    if (levelsBtn) levelsBtn.className = endOfLine ? 'ob p' : 'ob s';
    // The buttons live in per-column wrappers (LEVELS | REPLAY pair | NEXT);
    // a fully hidden column must collapse so the row re-centres instead of
    // leaving an empty gap (ascension / Nexus Point wins hide Next+Replay).
    const nextCol = nextBtn ? nextBtn.closest('.ov-btns-col') : null;
    if (nextCol) nextCol.style.display = endOfLine ? 'none' : '';
    _updateNexusWinButton(isNexusPoint);
    _updateConvergenceTrialWinButton(gi);
}

// Ensures the win overlay has a dedicated "Enter Convergence Trial" button.
// Shown after clearing one of the world's two convergence milestone levels
// (33% / 66% rule) when that completion unlocked (or re-unlocked) the world's
// trial. Mirrors the Nexus win button pattern: own id, static Next/Levels
// handlers untouched.
export function _updateConvergenceTrialWinButton(gi) {
    const container = document.querySelector('#ov-win .ov-btns');
    if (!container) return;
    const nextBtn = document.getElementById('btn-next-lvl');
    const target = (nextBtn && nextBtn.closest('.ov-btns-col')) || container;

    // Show condition: this win IS a trigger level AND the trial is now
    // unlocked AND not already completed. Everything else hides it.
    let show = false;
    let wi = null;
    try {
        wi = cur.world - 1;
        const level = globalThis.ALL[gi];
        const triggers = (typeof globalThis._egTrialTriggerLevels === 'function') ? globalThis._egTrialTriggerLevels(wi) : null;
        const isTrigger = !!(level && triggers && triggers.includes(level.li - 1));
        show = isTrigger
            && typeof globalThis._egIsTrialUnlocked === 'function' && globalThis._egIsTrialUnlocked(wi)
            && typeof globalThis._egIsTrialDone === 'function' && !globalThis._egIsTrialDone(wi);
    } catch (e) { show = false; }

    let btn = document.getElementById('btn-enter-trial-win');
    if (!btn) {
        btn = document.createElement('button');
        btn.id = 'btn-enter-trial-win';
        btn.className = 'ob y';
        btn.addEventListener('click', () => {
            hideResultOverlays();
            if (typeof globalThis._egLaunchCampaignTrial === 'function') globalThis._egLaunchCampaignTrial(wi);
            else goToLevelSelect();
        });
        target.appendChild(btn);
    }
    const label = (typeof t === 'function') ? t('btn_enter_trial_win') : null;
    btn.textContent = (label && label !== 'btn_enter_trial_win') ? label : '🌿 ENTER CONVERGENCE TRIAL';
    btn.style.display = show ? '' : 'none';
    if (show && target.classList && target.classList.contains('ov-btns-col')) {
        target.style.display = '';
    }
}

// Ensures the win overlay has a dedicated "Enter the Nexus" button.
// Created once, then shown only after the Nexus Point. Uses its own id so
// it never collides with the static Next/Levels handlers.
export function _updateNexusWinButton(show) {
    const container = document.querySelector('#ov-win .ov-btns');
    if (!container) return;
    // Prefer the NEXT column wrapper (the Nexus button occupies Next's slot
    // on Nexus Point wins, where Next itself is hidden); fall back to the
    // bare container for any markup without column wrappers.
    const nextBtn = document.getElementById('btn-next-lvl');
    const target = (nextBtn && nextBtn.closest('.ov-btns-col')) || container;
    let btn = document.getElementById('btn-enter-nexus-win');
    if (!btn) {
        btn = document.createElement('button');
        btn.id = 'btn-enter-nexus-win';
        btn.className = 'ob p';
        btn.addEventListener('click', () => {
            hideResultOverlays();
            if (typeof globalThis.showEndgameNexus === 'function') globalThis.showEndgameNexus();
            else goToLevelSelect();
        });
        target.appendChild(btn);
    } else if (btn.parentElement !== target) {
        target.appendChild(btn);
    }
    btn.textContent = t('scr_enter_nexus_short');
    btn.style.display = show ? '' : 'none';
    // On Nexus wins the Next column was hidden a moment earlier (endOfLine);
    // re-show the wrapper so the Nexus button is actually rendered.
    if (show && target.classList && target.classList.contains('ov-btns-col')) {
        target.style.display = '';
    }
}


//------------------------------------------------------------------------
//-------------------QUEST STAT HELPERS-----------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Returns true if the current level sits at a convergence milestone
// (33% or 66% through the world) and has not been flagged as an ascension level.
// Used for quest stat tracking inside checkWin().
export function checkIsConvergenceLevel(worldData, isAscensionLevel) {
    return isConvergenceLevel(worldData, isAscensionLevel);
}

// Returns true if this level completion is the one that finishes the entire world
// for the first time, and the world hasn't already been counted in quest stats.
// Prevents replays and already-counted worlds from triggering duplicate stat updates.
export function checkWorldJustCompleted(worldData, isFirstClear) {
    if (!isFirstClear) return false;

    const wi = cur.world - 1;
    const start = globalThis.WORLD_START_GI[wi];
    const allDone = worldData.data.every((_, li) => STATE.done.includes(start + li));
    if (!allDone) return false;

    STATE.questStats = STATE.questStats || {};
    const counted = STATE.questStats._worldsCountedList || [];
    return !counted.includes(wi);
}

// Returns true if this is a "large" level (200+ cells) and the player
// has the adjacency_matrix passive skill allocated.
export function checkIsLargeAdjMatrix() {
    const rows = cur.grid.length;
    const cols = cur.grid[0].length;
    return (rows * cols >= 200) && ptHasSkill('adjacency_matrix');
}





export function _getLevelSpecialStatus(level) {
    const worldData = globalThis.WORLDS[level.world - 1];
    // Tutorial-quest levels live outside the WORLDS array (world 15) - they
    // are never ascension/convergence/nexus levels.
    if (!worldData) return { isAscension: false, isConvergence: false, isNexusPoint: false };
    const wi = level.world - 1;
    const li = level.li - 1;
    const isNexusPoint = typeof globalThis.isNexusPointLevel === 'function'
        ? globalThis.isNexusPointLevel(wi, li)
        : (wi === 13 && li === worldData.data.length - 1);
    const isAscension = !isNexusPoint && level.li === worldData.data.length;
    const isConvergence = isConvergenceLevel(worldData, isAscension);
    return { isAscension, isConvergence, isNexusPoint };
}






//------------------------------------------------------------------------
//-------------------CHECK WIN (MAIN ENTRY POINT)-------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// Called after every valid cell change to check whether the puzzle is complete.
// If solved, halts the game, calculates the final score, fires all end-of-level
// hooks (achievements, rewards, quest stats), and shows the win overlay.

function checkWin() {
    if (!isPuzzleSolved()) return;

    // Monster levels hand off to the encounter chain instead of the normal
    // win flow. Campaign levels also run monsters (cur.campaignMonsters) but
    // must still complete as normal puzzle levels, so they are excluded.
    if (typeof globalThis._egIsActive === 'function' && globalThis._egIsActive()
        && !(cur && cur.campaignMonsters)) {
        if (typeof globalThis._egOnPuzzleComplete === 'function') {
            globalThis.dead = true;
            stopTimer();
            globalThis._egOnPuzzleComplete();
            return;           // skip all normal scoring / overlay logic
        }
    }

    // Map-device run: puzzle solved by start-of-level passives BEFORE the
    // encounter flag has flipped (initial puzzle only). The normal
    // win/scoring path must NOT run - the puzzle belongs to the encounter
    // chain (question modal → countdown → next puzzle). Suppress the normal
    // overlay here; _doStartLevel() will hand off to _egOnPuzzleComplete
    // immediately after it starts the encounter.
    if (window._egIsMapDeviceRun && cur && cur.isMonsterLevel
        && typeof globalThis._egOnPuzzleComplete === 'function'
        && typeof globalThis._egIsActive === 'function' && !globalThis._egIsActive()) {
        return;
    }


    // Stop any active visual effects and freeze the game state
    if (typeof window.clearActiveRandomWalkers === "function") window.clearActiveRandomWalkers();
    if (typeof globalThis.resetRecursionistState === "function") globalThis.resetRecursionistState(); // removes the DoF zombie + Residual skeletons
    globalThis.dead = true;
    stopTimer();

    if (typeof globalThis._arcaneFreeze_clearAllFrostAndStalagmites === 'function') {
        globalThis._arcaneFreeze_clearAllFrostAndStalagmites();     
    }

    // Gather level context
    const sol = cur.grid;
    const rows = sol.length;
    const cols = sol[0].length;
    const gi = cur.gIdx;
    const worldData = globalThis.WORLDS[cur.world - 1];
    if (!worldData) return;   // tutorial-quest levels bypass the normal win flow
    const _special = _getLevelSpecialStatus(cur);
    const isAscensionLevel = _special.isAscension;
    const isNexusPoint = !!_special.isNexusPoint;
    const isFirstClear = !STATE.done.includes(gi);

    if (isFirstClear) STATE.done.push(gi);

    // Campaign XP: a first clear grants the full amount, a replay a fraction
    // of it (see _egGrantCampaignLevelXP / EG_LEVELING_CONFIG). Endgame map
    // runs return above via _egOnPuzzleComplete and never reach this path.
    if (typeof globalThis._egGrantCampaignLevelXP === 'function') {
        try { globalThis._egGrantCampaignLevelXP(gi, isFirstClear); } catch (e) {}
    }
    // Region entry beat - fires on first clear of that world's designated trigger level
    /*
    if (isFirstClear && cur.li === (REGION_BEAT_TRIGGER_LEVEL[cur.world] || 1)) {
        showBeat('region_' + cur.world);
    }
    */

    _wdSyncSpriteToLevel(gi);    // move sprite to the just completed level

    // Track per-level mistake record for the "flawless world" achievement.
    // Always keep the best (lowest) mistake count across replays.
    if (!STATE.levelMistakes) STATE.levelMistakes = {};
    const prevMistakeRecord = STATE.levelMistakes[gi];
    if (prevMistakeRecord === undefined || globalThis.mistakeCount < prevMistakeRecord) {
        STATE.levelMistakes[gi] = globalThis.mistakeCount;
    }

    const elapsed = Math.round((Date.now() - globalThis.levelStartTime) / 1000);

    // Score
    const { pts, ptsAwarded, prevBest, mult } = calculateScore(rows, cols);
    save();
    document.getElementById('sc-disp').textContent = STATE.totalScore;

    // Achievements
    fireAchievements({ gi, rows, cols, elapsed, pts, ptsAwarded, prevBest, mult, isFirstClear });

    // Passive tree node rewards (gear_of_the_statistician & improved_gear)
    _ptApplyLevelCompleteRewards();

    // Bonus objective
    const bonusMet = evaluateBonusObjective(elapsed);

    if (typeof globalThis.triggerBanter === 'function') globalThis.triggerBanter('win');

// Render the win overlay content (buildReveal() is deferred until
    // #ov-win is actually visible - see the two branches below, and
    // finishQuiz()/skipQuiz() in quiz.js for the quiz-bonus path)
    renderWinOverlay({ gi, pts, ptsAwarded, prevBest, mult, elapsed, bonusMet, isAscensionLevel, isFirstClear, isNexusPoint });

    // World completion hooks - persist code unlocks immediately so they're
    // not lost if the player closes the game before the delayed modal shows.
    globalThis.checkWorldCodesSync();
    globalThis.checkWorldCompletion();

    // Show the win overlay (or quiz flow if the bonus type is 'quiz')
    if (bonusMet && cur.bonusType === 'quiz') {
        // ov-win itself isn't shown yet here - showQuiz() opens the separate
        // quiz-overlay first. buildReveal() runs later, in finishQuiz()/skipQuiz()
        // in quiz.js, right when ov-win actually becomes visible.
        setTimeout(() => globalThis.showQuiz(cur.world), 1500);
    } else {
        setTimeout(() => {
            document.getElementById('ov-win').classList.add('show');
            requestAnimationFrame(() => buildReveal());
        }, 1000);
    }

    // Codes popup delayed so it feels distinct from the win overlay
    setTimeout(() => globalThis.checkWorldCodes(), 2000);

    Audio_Manager.playSFX('win');

    // Quest stats update
    updateQuestStats('levelComplete', {
        gi,
        world: cur.world,
        diff: globalThis.curDiff,
        mods: { ...globalThis.curMods },
        mistakeCount: globalThis.mistakeCount,
        itemsUsed: globalThis.itemsUsedThisLevel,
        playerClass: STATE.playerClass,
        elapsed,
        bonusMet,
        isConvergence: checkIsConvergenceLevel(worldData, isAscensionLevel) && isFirstClear,
        worldJustCompleted: checkWorldJustCompleted(worldData, isFirstClear),
        worldIndex: cur.world - 1,
        luckyDropTriggered: false,
        timerSecsAtWin: globalThis.timerSecs,
        isLargeAdjMatrix: checkIsLargeAdjMatrix(),
    });

    if (typeof globalThis._endBlackSwan === "function") globalThis._endBlackSwan(false);
}