import { migrateQuestState } from './inference/inference-stats.js';

//------------------------------------------------------------------------
// Phase 3 step 3: live globalThis accessors for externally-mutated state.
// (auto-generated by dev/scratch/convert-step3.mjs - do not edit by hand)
//------------------------------------------------------------------------
try { Object.defineProperty(globalThis, 'STATE', { get() { return STATE; }, set(v) { STATE = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_confidenceIntervalActive', { get() { return _confidenceIntervalActive; }, set(v) { _confidenceIntervalActive = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_confidenceIntervalUsed', { get() { return _confidenceIntervalUsed; }, set(v) { _confidenceIntervalUsed = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_lawOfLargeNumbersNext', { get() { return _lawOfLargeNumbersNext; }, set(v) { _lawOfLargeNumbersNext = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_levelMistakesErased', { get() { return _levelMistakesErased; }, set(v) { _levelMistakesErased = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_levelTimeAdded', { get() { return _levelTimeAdded; }, set(v) { _levelTimeAdded = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_levelTimeLost', { get() { return _levelTimeLost; }, set(v) { _levelTimeLost = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, '_streakBonusFills', { get() { return _streakBonusFills; }, set(v) { _streakBonusFills = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'absorbedMistakes', { get() { return absorbedMistakes; }, set(v) { absorbedMistakes = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'axisLockEnabled', { get() { return axisLockEnabled; }, set(v) { axisLockEnabled = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'consecutiveCorrectFills', { get() { return consecutiveCorrectFills; }, set(v) { consecutiveCorrectFills = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'cur', { get() { return cur; }, set(v) { cur = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'dead', { get() { return dead; }, set(v) { dead = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'itemsUsedThisLevel', { get() { return itemsUsedThisLevel; }, set(v) { itemsUsedThisLevel = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'levelStartTime', { get() { return levelStartTime; }, set(v) { levelStartTime = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'luckyRewardClaimed', { get() { return luckyRewardClaimed; }, set(v) { luckyRewardClaimed = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'luckyTiles', { get() { return luckyTiles; }, set(v) { luckyTiles = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'mistakeCount', { get() { return mistakeCount; }, set(v) { mistakeCount = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'playerCurrentHP', { get() { return playerCurrentHP; }, set(v) { playerCurrentHP = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'playerCurrentMana', { get() { return playerCurrentMana; }, set(v) { playerCurrentMana = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'playerMaxHP', { get() { return playerMaxHP; }, set(v) { playerMaxHP = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'playerMaxMana', { get() { return playerMaxMana; }, set(v) { playerMaxMana = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'quizAnsweredCorrectly', { get() { return quizAnsweredCorrectly; }, set(v) { quizAnsweredCorrectly = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'revealedGrid', { get() { return revealedGrid; }, set(v) { revealedGrid = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'screenHistory', { get() { return screenHistory; }, set(v) { screenHistory = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'shieldActive', { get() { return shieldActive; }, set(v) { shieldActive = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'systemMarkedGrid', { get() { return systemMarkedGrid; }, set(v) { systemMarkedGrid = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'timerFrozen', { get() { return timerFrozen; }, set(v) { timerFrozen = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'userGrid', { get() { return userGrid; }, set(v) { userGrid = v; }, configurable: true }); } catch (e) {}
try { Object.defineProperty(globalThis, 'wrongGrid', { get() { return wrongGrid; }, set(v) { wrongGrid = v; }, configurable: true }); } catch (e) {}
//------------------------------------------------------------------------
//-------------------CONSTANTS & STATE-------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------
// Variables that describe what is happening in the current level.
// These are reset at the start of each level (see startLevel() in screens.js).
//------------------------------------------------------------------------

// --- Ad-hoc gameplay flags (namespaced 2026-09-10, Pass 4) ---
// These used to be loose window._* globals written from 12 files with no
// single owner. Now they live in one namespace; _resetLevelFlags() zeroes
// them all at level start (called from _resetClassLevelState in
// class-abilities.js).
window.LEVEL_FLAGS = {
    cursedImmune: false,      // Cursed Shield / The Witch: item curses do nothing this level
    goldenClockActive: false, // Golden Clock: the timer is frozen
    veiledCursedUsed: false,  // Veil of the Cursed: one-time curse redirection per level
    devTestActive: false,     // js/dev/dev-testing.js harness engaged (never set in normal play)
};

// Resets every LEVEL_FLAGS entry - call at level start/end so a flag that
// was left set (e.g. immunity that outlived the level) can never leak.
export function _resetLevelFlags() {
    window.LEVEL_FLAGS.cursedImmune = false;
    window.LEVEL_FLAGS.goldenClockActive = false;
    window.LEVEL_FLAGS.veiledCursedUsed = false;
    // devTestActive survives: it describes the session, not the level.
}


// --- Grid state ---

// The current level's puzzle object; set when a level starts.
let cur = null;

// Tracks the player's fills and marks per cell.
// e.g. userGrid[3][5] === 2 means row 3 col 5 is marked with ✕.
let userGrid = [];

// Tracks incorrectly filled cells (true = wrong fill).
// Used to show red ✕ marks and apply time penalties.
let wrongGrid = [];

// Tracks cells that were revealed by items or class abilities (true = revealed).
// Shown in green, counts as correct, and cannot be un-filled.
let revealedGrid = [];

// Tracks cells marked (✕) by an item, skill, or class ability rather than
// the player's own right-click, so they can be styled differently.
let systemMarkedGrid = [];



// --- Level tracking ---

// Date.now() timestamp recorded when the level begins.
// Used for accurate elapsed-time display on the win overlay,
// independent of any item-based time changes during the level.
let levelStartTime = 0;

// How many wrong fills the player has made this level.
// Used for score penalties and Hardcore mode failure tracking.
let mistakeCount = 0;

// Wrong fills that were absorbed by the Shield item or a class passive.
// Do not count toward mistakeCount or trigger penalties,
// but are tracked separately for achievements.
let absorbedMistakes = 0;


// --- Tooltip trackers (reset each level) ---

// Total seconds added to the timer this level (passive bonuses, streaks, items).
let _levelTimeAdded = 0;

// Total seconds lost to mistakes this level (penalties + variance collapse etc).
let _levelTimeLost = 0;

// How many mistakes have been erased/removed this level via Mistake Eraser items.
let _levelMistakesErased = 0;

// How many items the player has used this level; used for achievements.
let itemsUsedThisLevel = 0;

// Set to true when the timer hits 0 or a Hardcore mistake occurs.
// Prevents further input and stops the timer.
let dead = false;

// Set to true when the player answers the bonus quiz correctly.
// Read by scoring.js to determine whether to award the bonus reward.
let quizAnsweredCorrectly = false;


// --- Lucky tiles ---

// Stores keys for tiles that have a lucky reward this level.
// e.g. if row 3 col 5 is lucky, luckyTiles contains "3-5".
let luckyTiles = new Set();

// Ensures the lucky item reward can only be claimed once per level,
// even if the player fills multiple lucky tiles.
let luckyRewardClaimed = 0;


// --- Status flags ---

// When true, the next mistake is absorbed by the Shield instead of
// counting toward mistakeCount. Resets to false after absorbing one mistake.
let shieldActive = false;

// When true, the timer is paused. Set by the Freeze item or Absolute Zero
// class skill; cleared when the freeze duration expires.
let timerFrozen = false;

// When true, drag strokes are locked to the row or column of the starting cell.
let axisLockEnabled = false;


// --- Passive tree skill trackers ---
// These variables track runtime state for specific passive-tree skills.

// [sample_efficiency] Increments on each correct fill; resets on a time-costing mistake.
let consecutiveCorrectFills = 0;

// [law_of_large_numbers] Timestamp of the next auto-reveal tick; null when inactive.
let _lawOfLargeNumbersNext = null;

// [confidence_interval] True during the grace window that opens after a mistake.
let _confidenceIntervalActive = false;

// [confidence_interval] True if the grace window was just consumed,
// preventing back-to-back activations.
let _confidenceIntervalUsed = false;

// [streak_bonus] Consecutive correct fills since the last mistake.
let _streakBonusFills = 0;


// --- Player HP ---
// Base values are overwritten at level start using EG_PLAYER_STATS.baseHP.
// Kept at 100 here as a safe fallback before any level loads.
let playerMaxHP = 100;
let playerCurrentHP = 100;


// --- Player Mana ---
// Base values are overwritten at level start using EG_PLAYER_STATS.baseMana
// plus the aggregated mana bonus from gear and attributes. Kept at 0 here so
// no mana bar shows before any level loads.
let playerMaxMana = 0;
let playerCurrentMana = 0;


// --- Navigation history ---

// A stack of screen IDs representing the player's navigation path.
// Push when navigating forward; pop when going back (Escape key or Back button).
let screenHistory = [];


// --- Save slot system ---

// Number of save slots offered on the save-select screen.
export const SAVE_SLOT_COUNT = 20;

// localStorage key used to remember which slot is currently active.
export const ACTIVE_SLOT_KEY = 'stoxels_active_slot';

// localStorage key for the slot-name map ({ "1": "Alice", "7": "Hardcore Run" }).
// Stored OUTSIDE the save blobs on purpose: a name can exist for an empty
// slot (named before first save) and wiping a slot's data must never be
// blocked by or entangled with the naming metadata.
export const SLOT_NAMES_KEY = 'stoxels_slot_names';

// Returns the custom name for a save slot (string), or '' when unnamed.
export function getSlotName(slotNum) {
    try {
        const map = JSON.parse(localStorage.getItem(SLOT_NAMES_KEY) || '{}');
        return (map && typeof map[slotNum] === 'string') ? map[slotNum] : '';
    } catch {
        return '';
    }
}

// Writes a custom name for a save slot. Pass an empty/whitespace-only name
// to remove it (falls back to the default "SLOT {n}" label everywhere).
// Names are trimmed and hard-capped at 20 chars so the save-slot card
// layout can never overflow.
export function setSlotName(slotNum, name) {
    let map = {};
    try { map = JSON.parse(localStorage.getItem(SLOT_NAMES_KEY) || '{}') || {}; } catch { map = {}; }
    const clean = String(name || '').trim().slice(0, 20);
    if (clean) map[slotNum] = clean;
    else delete map[slotNum];
    try { localStorage.setItem(SLOT_NAMES_KEY, JSON.stringify(map)); } catch { /* storage full - name is cosmetic */ }
}


//------------------------------------------------------------------------
//------------------------GAME PERSISTENCE--------------------------------
//------------------------------------------------------------------------
// Handles saving and loading STATE to/from localStorage.
// STATE is the single source of truth for all persistent progress.
// Every screen that reads scores, inventory, or completion status reads from here.
//------------------------------------------------------------------------


// _makeEgGrid - builds an empty rows x cols grid (filled with null) for the
// endgame hub's inventory/stash storage. Shared by buildFreshState() and
// migrateOldSave() so the grid-building logic only lives in one place.
export function _makeEgGrid(rows, cols) {
    return Array.from({ length: rows }, () => Array(cols).fill(null));
}

// buildFreshState - returns a default STATE object for a brand-new save.
//                  Defines every field and its starting value in one place.
export function buildFreshState() {
    return {
        totalScore: 0,
        levelHS: {},
        levelMistakes: {},
        inventory: [],
        unlockedCodes: [],
        done: [],
        bonusDone: [],
        tutorialDone: false,
        mathGatePassed: [],
        primerPending: false,
        playerCharacter: null,

        // Lifetime tracking (for save-slot tooltip)
        totalTimePlayedSecs: 0,

        // Class progression
        playerClass: null,
        classPassiveLevel: 1,
        classActiveLevel: 1,
        classActive1Level: 1,
        classActive2Level: 1,
        classUpgradesAvailable: 0,
        classWorldsCompleted: [],
        classActiveChoice: 'active1',

        classHudHintUses: 0,   // how many times player has activated via slot 1/2

        // Skill hotbar: fixed-length array of skill ids (or null) for the 10
        // action-bar slots. Populated by ensureSkillHotbar() in
        // js/skills/skill-registry.js once the class defs are loaded.
        skillHotbar: new Array(10).fill(null),
        skillHotbarInit: false,   // auto-seed already done for this save
        skillHotbarOwner: null,   // '<class>|<ascendency>' the bar was seeded for

        // Charm system (js/skills/skill-charms.js). Every skill+rank pair is
        // its own charm item. Picked-up charms land in charmInventory; a
        // duplicate turns into a shard; 10 shards make an orb; an orb adds
        // +1% damage to the charm it is applied to. Placing a charm into one
        // of the 10 spell slots unlocks that spell in the spellbook.
        charmInventory: [],                        // [{ key, skillId, rank, orbs }]
        charmSlots: new Array(10).fill(null),      // charm key per spell slot
        charmShards: 0,                            // 0-9 spare shards (10 = 1 orb)
        charmOrbs: 0,                              // spendable Charm Orbs
        charmSeedKey: null,                        // '<class>|<ascendency>' starter charms were granted for

        // Class-change tokens (Nexus Ascension Level grants one; future
        // endgame sources may grant more). One token = one base-class switch.
        classChangeTokens: 0,
        classChangeUsed: false,

        // Ascendency progression
        playerAscendency: null,
        ascendencySkill1Level: 1,
        ascendencySkill2Level: 1,
        ascendencyWorldsCompleted: [],

        // Passive tree
        passiveTreePoints: 0,
        passiveTreeAllocated: new Set(),

        // Convergence levels (legacy 33%/66% milestone gis) + Convergence
        // Trials (Leveling Rework mini-maps, one per world, 'trial_<n>') and
        // Ascension Trials (mini-map chains behind each ascension level).
        convergenceDone: [],
        trialsDone: [],
        ascensionTrialsDone: [],

        // Nexus World (World 14) / Nexus Point progress.
        // Set to true on the first clear of the Nexus Point level; unlocks
        // the Nexus screen and the setup-screen "Enter the Nexus" button.
        nexusUnlocked: false,

        // Quests
        questStats: {},
        questsClaimed: [],
        questsNotified: [],

        // Achievement stats
        achStats: {},

        // endgame hub
        // Character leveling & attribute points (see endgame-leveling.js)
        playerLevel: 1,
        playerXP: 0,
        egAttrPoints: 0,
        egAttrAllocated: { str: 0, agi: 0, int: 0 },
        egEquipped: {},
        egInventory: _makeEgGrid(
            typeof globalThis.EG_INV_ROWS !== 'undefined' ? globalThis.EG_INV_ROWS : 5,
            typeof globalThis.EG_INV_COLS !== 'undefined' ? globalThis.EG_INV_COLS : 10
        ),
        egMapStash: (function(){
            // Tiered 16× infinite stashes - each tier is its own grid
            const tiers = (typeof globalThis.EG_MAP_TIER_COUNT !== 'undefined' ? globalThis.EG_MAP_TIER_COUNT : 16);
            const rows = (typeof globalThis.EG_MAP_STASH_INITIAL_ROWS !== 'undefined' ? globalThis.EG_MAP_STASH_INITIAL_ROWS : (typeof globalThis.EG_MAP_STASH_ROWS !== 'undefined' ? globalThis.EG_MAP_STASH_ROWS : 4));
            const cols = (typeof globalThis.EG_MAP_STASH_COLS !== 'undefined' ? globalThis.EG_MAP_STASH_COLS : 10);
            if (typeof globalThis._egMakeAllMapStashes === 'function') return globalThis._egMakeAllMapStashes();
            return Array.from({ length: tiers }, () => _makeEgGrid(rows, cols));
        })(),
        egCurrencyStash: _makeEgGrid(
            typeof globalThis.EG_CURRENCY_ROWS !== 'undefined' ? globalThis.EG_CURRENCY_ROWS : 2,
            typeof globalThis.EG_CURRENCY_COLS !== 'undefined' ? globalThis.EG_CURRENCY_COLS : 10
        ),
        egEssenceStash: _makeEgGrid(
            typeof globalThis.EG_ESSENCE_ROWS !== 'undefined' ? globalThis.EG_ESSENCE_ROWS : 6,
            typeof globalThis.EG_ESSENCE_COLS !== 'undefined' ? globalThis.EG_ESSENCE_COLS : 8
        ),
        egMapSlotItem: null,
        // Unique Stash - PoE-style collection tab: one slot per EG_UNIQUE_ITEMS entry
        egUniqueStash: {},
        egUniqueCollected: [],
    };
}

// _migrateCoreFields - fills in top-level fields missing from an older save.
export function _migrateCoreFields(s) {
    // Older saves may contain values written while an experimental modifier
    // was present. Keep score data numeric and never let a corrupt value turn
    // the HUD into NaN; high scores are repaired independently below.
    if (!Number.isFinite(Number(s.totalScore))) s.totalScore = 0;
    else s.totalScore = Number(s.totalScore);
    if (!s.levelHS || typeof s.levelHS !== 'object' || Array.isArray(s.levelHS)) s.levelHS = {};
    Object.keys(s.levelHS).forEach(gi => {
        const hs = s.levelHS[gi];
        if (!hs || !Number.isFinite(Number(hs.score))) delete s.levelHS[gi];
        else hs.score = Number(hs.score);
    });

    if (!s.bonusDone) s.bonusDone = [];
    if (s.tutorialDone === undefined) s.tutorialDone = false;
    if (!s.mathGatePassed) s.mathGatePassed = [];
    if (s.primerPending === undefined) s.primerPending = false;
    if (s.playerCharacter === undefined) s.playerCharacter = null;
    if (!s.levelMistakes) s.levelMistakes = {};
    if (!s.achStats) s.achStats = {};
    if (!s.convergenceDone) s.convergenceDone = [];
    if (!s.trialsDone) s.trialsDone = [];
    if (!s.ascensionTrialsDone) s.ascensionTrialsDone = [];
    if (s.nexusUnlocked === undefined) s.nexusUnlocked = false;

    // DefId rename: the "Tutor" item family was previously coded as
    // mistakeEraser / mistakeEraser4 / mistakeEraser6 / mistakeEraserAll.
    // Rewrites the stored defIds so old inventories keep working - runs
    // before any consumer reads the inventory.
    if (Array.isArray(s.inventory)) {
        const LEGACY_TUTOR_IDS = { mistakeEraser: 'tutor', mistakeEraser4: 'tutor4', mistakeEraser6: 'tutor6', mistakeEraserAll: 'tutorAll' };
        s.inventory.forEach(item => {
            if (item && LEGACY_TUTOR_IDS[item.defId]) item.defId = LEGACY_TUTOR_IDS[item.defId];
        });
    }

    if (s.totalTimePlayedSecs === undefined) s.totalTimePlayedSecs = 0;
}

// _migrateClassFields - fills in class-progression fields missing from an older save.
export function _migrateClassFields(s) {
    if (s.playerClass === undefined) s.playerClass = null;
    if (!s.classPassiveLevel) s.classPassiveLevel = 1;
    if (!s.classActiveLevel) s.classActiveLevel = 1;
    if (!s.classActive1Level) s.classActive1Level = s.classActiveLevel || 1;
    if (!s.classActive2Level) s.classActive2Level = s.classActiveLevel || 1;
    if (s.classUpgradesAvailable === undefined) s.classUpgradesAvailable = 0;
    if (!s.classWorldsCompleted) s.classWorldsCompleted = [];
    // Older saves stored classActiveChoice as a number; replace with the string default.
    if (!s.classActiveChoice || typeof s.classActiveChoice === 'number') s.classActiveChoice = 'active1';
    if (s.classHudHintUses === undefined) s.classHudHintUses = 0;
    if (s.classChangeTokens === undefined) s.classChangeTokens = 0;
    if (s.classChangeUsed === undefined) s.classChangeUsed = false;

    // Skill hotbar (js/skills/). Older saves predate the bar; _defaultSkillHotbar
    // is not loaded yet at init time, so seed empty slots and let
    // ensureSkillHotbar() fill them from the player's class on first render.
    if (!Array.isArray(s.skillHotbar) || s.skillHotbar.length !== 10) {
        s.skillHotbar = (typeof globalThis._defaultSkillHotbar === 'function')
            ? globalThis._defaultSkillHotbar(s)
            : new Array(10).fill(null);
    }
}

// _migrateCharmFields - fills in charm-system fields missing from an older
//                       save. The starter charms (one per owned skill at its
//                       current rank) are granted lazily by
//                       ensureCharmState() once the class defs are loaded, so
//                       this only has to guarantee the containers exist.
export function _migrateCharmFields(s) {
    if (!Array.isArray(s.charmInventory)) s.charmInventory = [];
    if (!Array.isArray(s.charmSlots) || s.charmSlots.length !== 10) {
        const slots = Array.isArray(s.charmSlots) ? s.charmSlots.slice(0, 10) : [];
        while (slots.length < 10) slots.push(null);
        s.charmSlots = slots;
    }
    if (!Number.isFinite(Number(s.charmShards))) s.charmShards = 0;
    if (!Number.isFinite(Number(s.charmOrbs))) s.charmOrbs = 0;
    if (s.charmSeedKey === undefined) s.charmSeedKey = null;
}

// _migrateAscendencyFields - fills in ascendency-progression fields missing from an older save.
export function _migrateAscendencyFields(s) {
    if (s.playerAscendency === undefined) s.playerAscendency = null;
    if (!s.ascendencySkill1Level) s.ascendencySkill1Level = 1;
    if (!s.ascendencySkill2Level) s.ascendencySkill2Level = 1;
    if (!s.ascendencyWorldsCompleted) s.ascendencyWorldsCompleted = [];
}

// _migratePassiveTreeFields - fills in passive-tree fields missing from an older save.
//                            passiveTreeAllocated is stored as a plain array in JSON,
//                            so it needs to become a Set at runtime.
export function _migratePassiveTreeFields(s) {
    if (!s.passiveTreePoints) s.passiveTreePoints = 0;
    if (!s.passiveTreeAllocated || !Array.isArray(s.passiveTreeAllocated)) {
        s.passiveTreeAllocated = new Set();
    } else {
        s.passiveTreeAllocated = new Set(s.passiveTreeAllocated);
    }
}

// _migrateEndgameFields - fills in endgame hub fields missing from an older save.
export function _migrateEndgameFields(s) {
    if (!s.playerLevel) s.playerLevel = 1;
    if (!s.playerXP) s.playerXP = 0;
    if (!s.egAttrPoints) s.egAttrPoints = 0;
    if (!s.egAttrAllocated) s.egAttrAllocated = { str: 0, agi: 0, int: 0 };
    if (!s.egEquipped) s.egEquipped = {};
    if (!s.egInventory) {
        s.egInventory = _makeEgGrid(
            typeof globalThis.EG_INV_ROWS !== 'undefined' ? globalThis.EG_INV_ROWS : 5,
            typeof globalThis.EG_INV_COLS !== 'undefined' ? globalThis.EG_INV_COLS : 10
        );
    }
    if (!s.egMapStash) {
        const tiers = (typeof globalThis.EG_MAP_TIER_COUNT !== 'undefined' ? globalThis.EG_MAP_TIER_COUNT : 16);
        const rows = (typeof globalThis.EG_MAP_STASH_INITIAL_ROWS !== 'undefined' ? globalThis.EG_MAP_STASH_INITIAL_ROWS : (typeof globalThis.EG_MAP_STASH_ROWS !== 'undefined' ? globalThis.EG_MAP_STASH_ROWS : 4));
        const cols = (typeof globalThis.EG_MAP_STASH_COLS !== 'undefined' ? globalThis.EG_MAP_STASH_COLS : 10);
        if (typeof globalThis._egMakeAllMapStashes === 'function') s.egMapStash = globalThis._egMakeAllMapStashes();
        else s.egMapStash = Array.from({ length: tiers }, () => _makeEgGrid(rows, cols));
    } else {
        // Migrate legacy flat stash (single grid) → tiered 16× stashes
        const isFlat = Array.isArray(s.egMapStash) && s.egMapStash.length > 0 && Array.isArray(s.egMapStash[0]) && s.egMapStash[0].length > 0 && !Array.isArray(s.egMapStash[0][0]);
        const isTiered = Array.isArray(s.egMapStash) && s.egMapStash.length === 16 && Array.isArray(s.egMapStash[0]) && Array.isArray(s.egMapStash[0][0]);
        if (isFlat && !isTiered) {
            const flat = s.egMapStash;
            const tiers2 = (typeof globalThis.EG_MAP_TIER_COUNT !== 'undefined' ? globalThis.EG_MAP_TIER_COUNT : 16);
            const rows2 = (typeof globalThis.EG_MAP_STASH_INITIAL_ROWS !== 'undefined' ? globalThis.EG_MAP_STASH_INITIAL_ROWS : 4);
            const cols2 = (typeof globalThis.EG_MAP_STASH_COLS !== 'undefined' ? globalThis.EG_MAP_STASH_COLS : 10);
            const tiered = Array.from({ length: tiers2 }, () => _makeEgGrid(rows2, cols2));
            for (let r = 0; r < flat.length; r++) {
                if (!Array.isArray(flat[r])) continue;
                for (let c = 0; c < flat[r].length; c++) {
                    const it = flat[r][c];
                    if (!it) continue;
                    const tier = (it.mapTier != null ? it.mapTier : 1);
                    const idx = Math.max(0, Math.min(tiers2-1, (Math.round(tier)||1)-1));
                    let placed = false;
                    for (let rr = 0; rr < tiered[idx].length && !placed; rr++) {
                        for (let cc = 0; cc < cols2; cc++) if (!tiered[idx][rr][cc]) { tiered[idx][rr][cc]=it; placed=true; break; }
                    }
                    if (!placed) { tiered[idx].push(Array(cols2).fill(null)); tiered[idx][tiered[idx].length-1][0]=it; }
                }
            }
            s.egMapStash = tiered;
        }
    }
    if (!s.egCurrencyStash) {
        s.egCurrencyStash = _makeEgGrid(
            typeof globalThis.EG_CURRENCY_ROWS !== 'undefined' ? globalThis.EG_CURRENCY_ROWS : 2,
            typeof globalThis.EG_CURRENCY_COLS !== 'undefined' ? globalThis.EG_CURRENCY_COLS : 10
        );
    }
    if (!s.egEssenceStash) {
        s.egEssenceStash = _makeEgGrid(
            typeof globalThis.EG_ESSENCE_ROWS !== 'undefined' ? globalThis.EG_ESSENCE_ROWS : 6,
            typeof globalThis.EG_ESSENCE_COLS !== 'undefined' ? globalThis.EG_ESSENCE_COLS : 8
        );
    }
    if (s.egMapSlotItem === undefined) s.egMapSlotItem = null;
    if (s.egMapStashActiveTier === undefined) s.egMapStashActiveTier = 1;
    if (!s.egUniqueStash || typeof s.egUniqueStash !== 'object' || Array.isArray(s.egUniqueStash)) s.egUniqueStash = {};
    // Normalise each entry to array
    for (const k of Object.keys(s.egUniqueStash)) {
        if (!Array.isArray(s.egUniqueStash[k])) s.egUniqueStash[k] = s.egUniqueStash[k] ? [s.egUniqueStash[k]] : [];
    }
    if (!s.egUniqueCollected || !Array.isArray(s.egUniqueCollected)) s.egUniqueCollected = [];
    // Derive collected from stash if missing (legacy)
    if (s.egUniqueCollected.length === 0) {
        for (const [uid, arr] of Object.entries(s.egUniqueStash)) {
            if (Array.isArray(arr) && arr.length > 0 && !s.egUniqueCollected.includes(uid)) s.egUniqueCollected.push(uid);
        }
        // also scan inventory for uniques that somehow stayed there
        if (Array.isArray(s.egInventory)) {
            for (let r=0;r<s.egInventory.length;r++) for(let c=0;c<(s.egInventory[r]||[]).length;c++){
                const it=s.egInventory[r]&&s.egInventory[r][c]; if(it&&it.isUnique&&it.baseId&&!s.egUniqueCollected.includes(it.baseId)) s.egUniqueCollected.push(it.baseId);
            }
        }
    }
}

// migrateOldSave - fills in any fields that are missing from an older save.
//                  Called before returning a loaded save so legacy data
//                  never causes undefined-access errors elsewhere.
export function migrateOldSave(s) {
    _migrateCoreFields(s);
    _migrateClassFields(s);
    _migrateAscendencyFields(s);
    _migratePassiveTreeFields(s);
    _migrateEndgameFields(s);
    _migrateCharmFields(s);
    // Quest containers. migrateQuestState is a REAL import now (from
    // js/inference/inference-stats.js). The state.js <-> inference-stats cycle is
    // safe: inference-stats has no top-level statements and migrateQuestState
    // is a hoisted declaration, so it exists before this body runs. The
    // guarded fallback from the 3.4.1 hotfix is retired.
    migrateQuestState(s);
}


//------------------------------------------------------------------------
//------------------------SAVE SLOT SYSTEM---------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------

// _slotKey - returns the localStorage key for a given slot number.
//           Slot 1 reuses the ORIGINAL 'stoxels' key on purpose - this is what makes
//           existing players' progress show up automatically as "Slot 1" with no
//           migration step required. Slots 2-20 get their own dedicated keys.
export function _slotKey(slotNum) {
    return slotNum === 1 ? 'stoxels' : `stoxels_slot_${slotNum}`;
}

// Returns the currently active slot number (1-20), or null if none chosen yet
// in this browser (e.g. very first load, before the save-select screen ran).
export function getActiveSlot() {
    const s = parseInt(localStorage.getItem(ACTIVE_SLOT_KEY), 10);
    return (s >= 1 && s <= SAVE_SLOT_COUNT) ? s : null;
}

// Persists which slot is currently active.
export function setActiveSlot(slotNum) {
    localStorage.setItem(ACTIVE_SLOT_KEY, String(slotNum));
}

// Reads the raw JSON for a specific slot without making it active.
export function loadRawSaveFromSlot(slotNum) {
    try {
        return JSON.parse(localStorage.getItem(_slotKey(slotNum)) || 'null');
    } catch {
        return null;
    }
}

// Migrates a legacy slot name that was stored inside the save blob
// (raw.slotName) into the dedicated names map - used by getSlotSummary so
// names written by future in-save storage still show up after the split.
export function _migrateSlotNameFromBlob(slotNum, raw) {
    if (!raw || typeof raw.slotName !== 'string') return;
    if (!getSlotName(slotNum)) setSlotName(slotNum, raw.slotName);
    delete raw.slotName;
    try { localStorage.setItem(_slotKey(slotNum), JSON.stringify(raw)); } catch { /* cosmetic only */ }
}

// Lightweight summary used to render the save-slot select screen.
export function getSlotSummary(slotNum) {
    const raw = loadRawSaveFromSlot(slotNum);
    // Legacy blobs may carry a slotName field - promote it to the names map.
    if (raw && typeof raw.slotName === 'string') _migrateSlotNameFromBlob(slotNum, raw);
    if (!raw) return { slot: slotNum, empty: true, name: getSlotName(slotNum) };
    return {
        slot: slotNum,
        empty: false,
        name: getSlotName(slotNum),
        totalScore: raw.totalScore || 0,
        levelsDone: (raw.done || []).length,
        playerCharacter: raw.playerCharacter || null,
        playerClass: raw.playerClass || null,
        playerAscendency: raw.playerAscendency || null,
        tutorialDone: !!raw.tutorialDone,
        // --- Extended stats for the save-slot tooltip ---
        // NOTE: sourced from raw.questStats (per-slot), NOT raw.achStats
        // (achStats is a cross-slot/global store and is never populated
        // per-slot - see achievements.js, which persists to ACH_SAVE_KEY).
        bonusDone: raw.bonusDone || [],
        levelHS: raw.levelHS || {},
        classPassiveLevel: raw.classPassiveLevel || 1,
        classActive1Level: raw.classActive1Level || 1,
        classActive2Level: raw.classActive2Level || 1,
        ascendencySkill1Level: raw.ascendencySkill1Level || 1,
        ascendencySkill2Level: raw.ascendencySkill2Level || 1,
        questsClaimedCount: (raw.questsClaimed || []).length,
        totalTimePlayedSecs: raw.totalTimePlayedSecs || 0,
        playerLevel: raw.playerLevel || 1,

        lifetimeTilesRevealed: (raw.questStats && raw.questStats.lifetimeTilesRevealed) || 0,
        lifetimeTilesFilled: (raw.questStats && raw.questStats.lifetimeTilesFilled) || 0,
        lifetimeMistakesMade: (raw.questStats && raw.questStats.lifetimeMistakesMade) || 0,
        itemsUsedTotal: (raw.questStats && raw.questStats.itemsUsedTotal) || 0,
        classAbilitiesUsed: (raw.questStats && raw.questStats.classAbilitiesUsed) || 0,
        passivePointsObtained: (raw.questStats && raw.questStats.lifetimePassivePointsObtained) || 0,
        questionsCorrect: (raw.questStats && raw.questStats.questionsCorrect) || 0,
    };
}

// _stoxAnyItem - true when v (a stash grid / object-of-arrays / item) holds
// at least one real item. Used by the save() degraded-state guard so it can
// tell "player owns nothing endgame" apart from "hub mirrors failed to load".
export function _stoxAnyItem(v) {
    if (!v) return false;
    if (Array.isArray(v)) {
        for (const x of v) {
            if (x && typeof x === 'object' && (x.id || x.baseId)) return true;
            if (Array.isArray(x) && _stoxAnyItem(x)) return true;
        }
        return false;
    }
    if (typeof v === 'object') {
        for (const k in v) {
            if (Array.isArray(v[k]) && _stoxAnyItem(v[k])) return true;
            if (v[k] && typeof v[k] === 'object' && !Array.isArray(v[k]) && (v[k].id || v[k].baseId)) return true;
        }
    }
    return false;
}

// _stoxHasEndgameProgress - true when the save shows any sign the player
// ever ENGAGED with the endgame (atlas unlocks, gold, hub metadata, an
// equipped/inventoried item). Campaign-only characters (the normal path
// since the leveling rework hands out XP from story level 1) legitimately
// own zero endgame items - the presence of these fields distinguishes
// "never entered the endgame" from "hub mirrors failed to load".
export function _stoxHasEndgameProgress(v) {
    return !!v && (
        (v.egGold !== undefined && v.egGold !== null && Number(v.egGold) !== 0) ||
        (v.egAtlasCompleted && typeof v.egAtlasCompleted === 'object' && Object.keys(v.egAtlasCompleted).length > 0) ||
        (v.egHubVisited === true) ||
        (v.egHighestMapTier !== undefined && v.egHighestMapTier !== null && Number(v.egHighestMapTier) > 0) ||
        (v.egAttrAllocated && typeof v.egAttrAllocated === 'object' &&
            Object.values(v.egAttrAllocated).some(n => Number(n) > 0)) ||
        _stoxAnyItem(v.egEquipped) || _stoxAnyItem(v.egInventory) ||
        _stoxAnyItem(v.egMapStash) || _stoxAnyItem(v.egCurrencyStash) ||
        _stoxAnyItem(v.egEssenceStash) || _stoxAnyItem(v.egUniqueStash) ||
        !!(v.egMapSlotItem && (v.egMapSlotItem.id || v.egMapSlotItem.baseId))
    );
}

// save - serialises STATE into the currently active slot (defaults to
// Slot 1 if nothing has been explicitly chosen yet, matching old behaviour).
//
// Safety net (added 2026-09 after a refactor-session incident where a
// stale/empty hub wiped a leveled character's stash):
//   1. ROLLING BACKUPS - the first write to a slot in a browser session
//      snapshots the previous save into <key>_backup_1 (and shifts the old
//      backup_1 into _backup_2). The last two pre-session states therefore
//      stay recoverable at all times (see tools/save-doctor.html).
//   2. DEGRADED-WRITE GUARD - refuses to overwrite a save with endgame
//      PROGRESS (see _stoxHasEndgameProgress) whose ENTIRE endgame
//      inventory is empty (all of egEquipped/egInventory/egMapStash/
//      egCurrencyStash/egEssenceStash/egUniqueStash), because that pattern
//      in practice only occurs when the hub's mirrors failed to load
//      (script error / stale cache). Saves with NO endgame progress are
//      exempt: a campaign-only character at any level legitimately owns
//      nothing (fixes the false refusal after the leveling rework made
//      playerLevel 2+ reachable before the first hub visit).
//      Intentional resets are unaffected (the slot key is wiped first, so
//      there is no previous save to compare against).
export function save() {
    const slot = getActiveSlot() || 1;
    const toSave = { ...STATE };
    if (STATE.passiveTreeAllocated instanceof Set) {
        toSave.passiveTreeAllocated = [...STATE.passiveTreeAllocated];
    }
    const key = _slotKey(slot);
    let json;
    try {
        json = JSON.stringify(toSave);
    } catch (e) {
        console.error('[save] serialisation failed - previous save left untouched', e);
        return;
    }
    const raw = localStorage.getItem(key);
    let prev = null;
    try { prev = raw ? JSON.parse(raw) : null; } catch (e) { prev = null; }
    const endgameEmpty =
        (!toSave.egEquipped || Object.keys(toSave.egEquipped).length === 0) &&
        !_stoxAnyItem(toSave.egInventory) &&
        !_stoxAnyItem(toSave.egMapStash) &&
        !_stoxAnyItem(toSave.egCurrencyStash) &&
        !_stoxAnyItem(toSave.egEssenceStash) &&
        !_stoxAnyItem(toSave.egUniqueStash) &&
        !(toSave.egMapSlotItem && (toSave.egMapSlotItem.id || toSave.egMapSlotItem.baseId));
    if (prev && (prev.playerLevel || 0) > 1 && _stoxHasEndgameProgress(prev) && endgameEmpty && !window._stoxAllowDegradedSave) {
        // Log once per session - a save-deadlock with a spamming console helps
        // nobody. The override lets a genuinely intentional full reset (or a
        // recovered save) proceed; everything is documented in save-doctor.
        if (!window._stoxSaveRefusalLogged) {
            console.error('[save] REFUSED to overwrite: previous save has playerLevel', prev.playerLevel,
                'but this save has NO endgame items at all - that pattern means the hub state failed to load,',
                'not that the player sold everything. Previous save left untouched.',
                'Inspect/recover via tools/save-doctor.html. If this refusal is wrong (you really do own nothing),',
                'run  window._stoxAllowDegradedSave = true  in this console to override for this session.');
            window._stoxSaveRefusalLogged = true;
        }
        window._stoxLastSaveRefusal = { at: Date.now(), prevLevel: prev.playerLevel, slot };
        return;
    }
    // Rolling backups - first write per session snapshots the pre-session state.
    if (window._stoxLastSavedKey !== key) {
        try {
            const b1 = localStorage.getItem(key + '_backup_1');
            if (b1) localStorage.setItem(key + '_backup_2', b1);
            if (raw) localStorage.setItem(key + '_backup_1', raw);
        } catch (e) { /* storage full - the main save still proceeds */ }
    }
    try {
        localStorage.setItem(key, json);
        // Only mark the backup as rotated after the real write succeeded, so a
        // failed write (quota) retries the rotation on the next save.
        window._stoxLastSavedKey = key;
    } catch (e) {
        console.error('[save] write failed (storage full?) - previous save left untouched', e);
        return;
    }
}

// Loads (or freshly creates) the STATE for a given slot, marks it active,
// and persists immediately. Call this when the player picks a slot on the
// save-select screen.
export function loadStateFromSlot(slotNum) {
    let raw = loadRawSaveFromSlot(slotNum);
    if (raw) {
        migrateOldSave(raw);
    } else {
        raw = buildFreshState();
    }
    setActiveSlot(slotNum);
    STATE = raw;
    // New slot = new data: clear this session's hub load/save latches so the
    // hub re-syncs its mirrors from the freshly loaded STATE (and so a load
    // failure bound to the previous slot does not poison this one).
    window._stoxHubStateLoaded = false;
    window._stoxHubLoadFailed = false;
    // Slot switch resync: the live hub mirrors (_egEquipped, _egInventory,
    // currency/essence/map stashes, ...) still hold the PREVIOUS slot's data
    // until something re-runs the load. showEndgameHub does - but the
    // tutorial never opens the hub before it needs combat stats, so a fresh
    // character would fight with the old slot's gear (inflated HP / mana /
    // absorption / damage on the avatar bars, and stash grants landing in
    // the wrong mirror). Re-sync immediately, mirroring the parse-time
    // completion pattern in endgame-hub.js.
    if (typeof globalThis._egLoadHubState === 'function') {
        window._stoxHubLoadInProgress = true;
        try {
            globalThis._egLoadHubState();
            window._stoxHubStateLoaded = true;
        } catch (e) {
            window._stoxHubLoadFailed = true;
            console.error('[hub] slot-switch re-sync failed - save-writes BLOCKED until reload', e);
        } finally {
            window._stoxHubLoadInProgress = false;
        }
    }
    // Re-sync endgame leveling (player level / attribute points) to the newly loaded save.
    if (typeof globalThis._egLoadLevelingState === 'function') globalThis._egLoadLevelingState();
    save();
    return STATE;
}

// Wipes ONLY the given slot's save data. Used by the "Reset Progress" flow
// on the title screen - achievements live in their own global key
// (ACH_SAVE_KEY, achievements.js) and are never touched by this.
// The custom slot name is cleared too: a deleted save should not leave a
// stale label on the now-empty slot.
export function wipeSlot(slotNum) {
    localStorage.removeItem(_slotKey(slotNum));
    setSlotName(slotNum, '');
    if (typeof globalThis.resetAllBeatsForSlot === 'function') globalThis.resetAllBeatsForSlot(slotNum);
}

// initState - called once at script load, before the player has necessarily
// picked a slot on the new save-select screen. Falls back to the last
// active slot (persisted across reloads), then to legacy Slot 1 data if
// present, then to a blank state. The save-select screen overwrites STATE
// properly as soon as Play is clicked.
export function initState() {
    const activeSlot = getActiveSlot();
    if (activeSlot) {
        const saved = loadRawSaveFromSlot(activeSlot);
        if (saved) {
            migrateOldSave(saved);
            return saved;
        }
    }
    const legacy = loadRawSaveFromSlot(1);
    if (legacy) {
        migrateOldSave(legacy);
        return legacy;
    }
    return buildFreshState();
}

// STATE - the single source of truth for all persistent progress.
// Declared here (rather than in the CONSTANTS & STATE section) because its
// initial value depends on initState(), which in turn depends on
// buildFreshState()/migrateOldSave() - all defined earlier in this file.
let STATE = initState();


//------------------------------------------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------
//------------------------------------------------------------------------