import js from '@eslint/js';
import globals from 'globals';

export default [
    {
        ignores: [
            'node_modules/**',
            'generated/**',      // build output (regenerated by npm run build)
            'images/**',
            'audio/**',
            'animations/**',
            'css/**',
            // Copy-paste template, never shipped (also excluded from
            // tools/module-manifest.json); it references EG_BOSS_* globals
            // only after being copied into a real boss file.
            'js/combat/bosses/boss-template.js',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2023,
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.node,
            },
        },
        rules: {
            // Empty catch blocks are the codebase's deliberate swallow
            // pattern (globalThis bridges, optional feature probes).
            'no-empty': ['error', { allowEmptyCatch: true }],

            // Warnings, not errors, on purpose: project policy keeps
            // suspected-dead code around for a later decision ("kept for a
            // later dead-code decision, not deleted" - universal-spells.js),
            // and ~50 such findings predate this config. They are still
            // reported on every run so they can be burned down; unused
            // parameters and caught errors are ignored entirely.
            'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],

            // Legacy pattern used deliberately across the classic-script
            // era files: function declarations rebound at runtime.
            'no-func-assign': 'off',

            // Not part of the recommended set this codebase was written
            // against; flags its write-then-overwrite state resets.
            'no-useless-assignment': 'off',
        },
    },
];
